/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  corePlugins: {
    preflight: false,
  },
  theme: {
    extend: {
      colors: {
        'inverse-primary': '#ffb597',
        background: '#fcf9f4',
        'on-surface': '#1c1c19',
        'on-surface-variant': '#52443e',
        primary: '#8f4d2f',
        error: '#ba1a1a',
        'on-secondary-fixed': '#2c1600',
        'primary-fixed': '#ffdbcd',
        'primary-container': '#d48563',
        'inverse-surface': '#31302d',
        outline: '#6d4b3b',
        'on-tertiary-container': '#3b2f1d',
        secondary: '#825422',
        'on-tertiary-fixed-variant': '#524531',
        'error-container': '#ffdad6',
        surface: '#fcf9f4',
        'on-primary-fixed': '#360f00',
        'on-error-container': '#93000a',
        'surface-variant': '#e5e2dd',
        'on-background': '#1c1c19',
        'on-tertiary-fixed': '#241a09',
        'tertiary-fixed-dim': '#d8c3aa',
        'outline-variant': '#8d6a58',
        'on-primary': '#ffffff',
        'on-primary-fixed-variant': '#72361a',
        'surface-bright': '#fcf9f4',
        'surface-tint': '#8f4d2f',
        'tertiary-fixed': '#f5dfc5',
        'on-secondary-fixed-variant': '#663d0b',
        'secondary-fixed': '#ffdcbd',
        'primary-fixed-dim': '#ffb597',
        'on-primary-container': '#552006',
        'surface-dim': '#dcdad5',
        'surface-container': '#f0ede9',
        'secondary-fixed-dim': '#f7bb7e',
        'on-secondary-container': '#784c1a',
        'on-secondary': '#ffffff',
        'tertiary-container': '#a8967e',
        'surface-container-lowest': '#ffffff',
        'inverse-on-surface': '#f3f0eb',
        'secondary-container': '#fdc083',
        'surface-container-highest': '#e5e2dd',
        'surface-container-low': '#f6f3ee',
        'on-error': '#ffffff',
        'surface-container-high': '#ebe8e3',
        tertiary: '#6b5c47',
        'on-tertiary': '#ffffff',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      fontFamily: {
        headline: ['"Noto Serif TC"', 'serif'],
        body: ['Manrope', 'sans-serif'],
        label: ['Manrope', 'sans-serif'],
      },
    },
  },
  plugins: [],
};
