CREATE TABLE IF NOT EXISTS product_orders (
    id INT AUTO_INCREMENT PRIMARY KEY,
    product_code VARCHAR(40) NOT NULL,
    product_name VARCHAR(120) NOT NULL,
    customer_email VARCHAR(255) NOT NULL,
    customer_name VARCHAR(200) NULL,
    amount_cents INT NOT NULL,
    currency VARCHAR(3) NOT NULL DEFAULT 'usd',
    status VARCHAR(30) NOT NULL DEFAULT 'pending_payment',
    payment_status VARCHAR(20) NOT NULL DEFAULT 'pending',
    stripe_payment_intent_id VARCHAR(255) UNIQUE NULL,
    stripe_charge_id VARCHAR(255) NULL,
    notes TEXT NULL,
    fulfilled_at TIMESTAMP NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT chk_product_order_status CHECK (status IN ('pending_payment', 'paid', 'fulfilled', 'cancelled')),
    CONSTRAINT chk_product_order_payment_status CHECK (payment_status IN ('pending', 'succeeded', 'failed', 'refunded', 'partially_refunded')),
    INDEX idx_product_orders_product_code (product_code),
    INDEX idx_product_orders_customer_email (customer_email),
    INDEX idx_product_orders_status (status),
    INDEX idx_product_orders_payment_status (payment_status),
    INDEX idx_product_orders_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
