export const ADMIN_COPY = {
  'zh-CN': {
    common: {
      loading: '加载中...',
      loadingDetails: '加载详情中...',
      none: '无',
      close: '关闭',
      minuteUnit: '分钟',
      languageSwitcher: '语言切换',
    },
    layout: {
      brand: '按摩预约系统',
      dashboard: '控制台',
      bookings: '预约管理',
      availability: '时间管理',
      customers: '客户管理',
      logout: '退出登录',
      loading: '加载中...',
    },
    login: {
      title: '管理员登录',
      email: '邮箱',
      password: '密码',
      submit: '登录',
      submitting: '登录中...',
      backHome: '← 返回主页',
      failed: '登录失败',
    },
    dashboard: {
      loadError: '无法加载控制台数据',
      welcome: '欢迎',
      stats: {
        todayBookings: '今日预约',
        weekBookings: '本周预约',
        monthRevenue: '本月收入',
        customerCount: '客户总数',
        pendingRescheduleRequests: '待处理改期',
      },
      upcomingTitle: '即将到来的预约',
      emptyUpcoming: '暂无即将到来的预约',
    },
    bookings: {
      title: '预约管理',
      detailTitle: '预约详情',
      loadListError: '无法加载预约列表',
      loadDetailError: '无法加载预约详情',
      updateSuccess: '预约状态已更新',
      updateFailed: '更新预约状态失败',
      rescheduleSuccess: '预约已改期',
      rescheduleFailed: '改期失败',
      reviewApproveSuccess: '改期申请已批准',
      reviewRejectSuccess: '改期申请已拒绝',
      reviewFailed: '处理改期申请失败',
      adminCancelledReason: '管理员取消预约',
      filters: {
        allStatuses: '全部状态',
        searchPlaceholder: '搜索客户 / 邮箱 / 电话',
        search: '搜索',
      },
      empty: '暂无符合条件的预约',
      selectHint: '请选择左侧预约查看详情',
      fields: {
        bookingId: '预约编号',
        customer: '客户',
        email: '邮箱',
        phone: '电话',
        service: '服务',
        duration: '时长',
        time: '时间',
        price: '价格',
        bookingStatus: '预约状态',
        paymentStatus: '支付状态',
        paymentIntent: 'Payment Intent',
        manageToken: '管理令牌',
      },
      notes: '客户备注',
      actions: {
        confirmBooking: '确认预约',
        confirmArrival: '确认到店',
        markCompleted: '完成服务',
        markNoShow: '标记未到店',
        cancelBooking: '取消预约',
        submitReschedule: '提交改期',
        approve: '批准',
        reject: '拒绝',
      },
      attendance: {
        notArrived: '未到店',
        arrived: '已到店',
      },
      reschedule: {
        title: '管理员直接改期',
        startTime: '开始时间',
        endTime: '结束时间',
        adminNote: '管理员备注（可选）',
      },
      requests: {
        title: '改期申请',
        empty: '暂无改期申请',
        noCustomerNote: '无客户备注',
        approvePrompt: '审核备注（可选）',
        rejectPrompt: '拒绝原因（可选）',
      },
    },
    customers: {
      title: '客户管理',
      detailTitle: '客户详情',
      loadListError: '无法加载客户列表',
      loadDetailError: '无法加载客户详情',
      searchPlaceholder: '搜索姓名 / 邮箱 / 电话',
      search: '搜索',
      empty: '暂无客户记录',
      selectHint: '请选择左侧客户查看详情',
      bookingCountSuffix: '次预约',
      fields: {
        name: '姓名',
        email: '邮箱',
        phone: '电话',
        createdAt: '客户创建时间',
        bookingCount: '预约次数',
        totalSpent: '累计消费',
      },
      historyTitle: '预约历史',
      emptyHistory: '暂无预约历史',
    },
    availability: {
      title: '时间管理',
      loadErrorPrefix: '加载失败: ',
      updateHoursSuccess: '营业时间已更新',
      updateTimeSuccess: '时间已更新',
      createBlockSuccess: '屏蔽时间已添加',
      createBlockFailedPrefix: '添加失败: ',
      updateFailedPrefix: '更新失败: ',
      deleteBlockSuccess: '屏蔽时间已删除',
      deleteBlockFailedPrefix: '删除失败: ',
      deleteConfirm: '确定要删除这个屏蔽时间吗？',
      businessHoursTitle: '营业时间',
      blocksTitle: '屏蔽时间',
      addBlock: '+ 添加屏蔽时间',
      emptyBlocks: '暂无屏蔽时间',
      statusOpen: '营业',
      statusClosed: '休息',
      setClosed: '设为休息',
      setOpen: '设为营业',
      delete: '删除',
      modal: {
        title: '添加屏蔽时间',
        startTime: '开始时间',
        endTime: '结束时间',
        reason: '原因（可选）',
        reasonPlaceholder: '例如：休假、临时有事',
        cancel: '取消',
        submit: '添加',
      },
      days: ['周日', '周一', '周二', '周三', '周四', '周五', '周六'],
    },
    statuses: {
      pending: '待处理',
      confirmed: '已确认',
      arrived: '已到店',
      completed: '已完成',
      cancelled: '已取消',
      no_show: '未到店',
      expired: '已过期',
      succeeded: '支付成功',
      failed: '支付失败',
      refunded: '已退款',
      partially_refunded: '部分退款',
      approved: '已批准',
      rejected: '已拒绝',
    },
    fallback: {
      notFound: '页面未找到',
    },
  },
  'zh-TW': {
    common: {
      loading: '載入中...',
      loadingDetails: '載入詳情中...',
      none: '無',
      close: '關閉',
      minuteUnit: '分鐘',
      languageSwitcher: '語言切換',
    },
    layout: {
      brand: '按摩預約系統',
      dashboard: '控制台',
      bookings: '預約管理',
      availability: '時間管理',
      customers: '客戶管理',
      logout: '登出',
      loading: '載入中...',
    },
    login: {
      title: '管理員登入',
      email: '信箱',
      password: '密碼',
      submit: '登入',
      submitting: '登入中...',
      backHome: '← 返回首頁',
      failed: '登入失敗',
    },
    dashboard: {
      loadError: '無法載入控制台資料',
      welcome: '歡迎',
      stats: {
        todayBookings: '今日預約',
        weekBookings: '本週預約',
        monthRevenue: '本月收入',
        customerCount: '客戶總數',
        pendingRescheduleRequests: '待處理改期',
      },
      upcomingTitle: '即將到來的預約',
      emptyUpcoming: '暫無即將到來的預約',
    },
    bookings: {
      title: '預約管理',
      detailTitle: '預約詳情',
      loadListError: '無法載入預約列表',
      loadDetailError: '無法載入預約詳情',
      updateSuccess: '預約狀態已更新',
      updateFailed: '更新預約狀態失敗',
      rescheduleSuccess: '預約已改期',
      rescheduleFailed: '改期失敗',
      reviewApproveSuccess: '改期申請已批准',
      reviewRejectSuccess: '改期申請已拒絕',
      reviewFailed: '處理改期申請失敗',
      adminCancelledReason: '管理員取消預約',
      filters: {
        allStatuses: '全部狀態',
        searchPlaceholder: '搜尋客戶 / 信箱 / 電話',
        search: '搜尋',
      },
      empty: '暫無符合條件的預約',
      selectHint: '請選擇左側預約查看詳情',
      fields: {
        bookingId: '預約編號',
        customer: '客戶',
        email: '信箱',
        phone: '電話',
        service: '服務',
        duration: '時長',
        time: '時間',
        price: '價格',
        bookingStatus: '預約狀態',
        paymentStatus: '支付狀態',
        paymentIntent: 'Payment Intent',
        manageToken: '管理令牌',
      },
      notes: '客戶備註',
      actions: {
        confirmBooking: '確認預約',
        confirmArrival: '確認到店',
        markCompleted: '完成服務',
        markNoShow: '標記未到店',
        cancelBooking: '取消預約',
        submitReschedule: '提交改期',
        approve: '批准',
        reject: '拒絕',
      },
      attendance: {
        notArrived: '未到店',
        arrived: '已到店',
      },
      reschedule: {
        title: '管理員直接改期',
        startTime: '開始時間',
        endTime: '結束時間',
        adminNote: '管理員備註（可選）',
      },
      requests: {
        title: '改期申請',
        empty: '暫無改期申請',
        noCustomerNote: '無客戶備註',
        approvePrompt: '審核備註（可選）',
        rejectPrompt: '拒絕原因（可選）',
      },
    },
    customers: {
      title: '客戶管理',
      detailTitle: '客戶詳情',
      loadListError: '無法載入客戶列表',
      loadDetailError: '無法載入客戶詳情',
      searchPlaceholder: '搜尋姓名 / 信箱 / 電話',
      search: '搜尋',
      empty: '暫無客戶紀錄',
      selectHint: '請選擇左側客戶查看詳情',
      bookingCountSuffix: '次預約',
      fields: {
        name: '姓名',
        email: '信箱',
        phone: '電話',
        createdAt: '客戶建立時間',
        bookingCount: '預約次數',
        totalSpent: '累計消費',
      },
      historyTitle: '預約歷史',
      emptyHistory: '暫無預約歷史',
    },
    availability: {
      title: '時間管理',
      loadErrorPrefix: '載入失敗: ',
      updateHoursSuccess: '營業時間已更新',
      updateTimeSuccess: '時間已更新',
      createBlockSuccess: '屏蔽時段已新增',
      createBlockFailedPrefix: '新增失敗: ',
      updateFailedPrefix: '更新失敗: ',
      deleteBlockSuccess: '屏蔽時段已刪除',
      deleteBlockFailedPrefix: '刪除失敗: ',
      deleteConfirm: '確定要刪除這個屏蔽時段嗎？',
      businessHoursTitle: '營業時間',
      blocksTitle: '屏蔽時間',
      addBlock: '+ 新增屏蔽時間',
      emptyBlocks: '暫無屏蔽時間',
      statusOpen: '營業',
      statusClosed: '休息',
      setClosed: '設為休息',
      setOpen: '設為營業',
      delete: '刪除',
      modal: {
        title: '新增屏蔽時間',
        startTime: '開始時間',
        endTime: '結束時間',
        reason: '原因（可選）',
        reasonPlaceholder: '例如：休假、臨時有事',
        cancel: '取消',
        submit: '新增',
      },
      days: ['週日', '週一', '週二', '週三', '週四', '週五', '週六'],
    },
    statuses: {
      pending: '待處理',
      confirmed: '已確認',
      arrived: '已到店',
      completed: '已完成',
      cancelled: '已取消',
      no_show: '未到店',
      expired: '已過期',
      succeeded: '支付成功',
      failed: '支付失敗',
      refunded: '已退款',
      partially_refunded: '部分退款',
      approved: '已批准',
      rejected: '已拒絕',
    },
    fallback: {
      notFound: '找不到頁面',
    },
  },
  en: {
    common: {
      loading: 'Loading...',
      loadingDetails: 'Loading details...',
      none: 'None',
      close: 'Close',
      minuteUnit: 'min',
      languageSwitcher: 'Language switcher',
    },
    layout: {
      brand: 'Massage Booking System',
      dashboard: 'Dashboard',
      bookings: 'Bookings',
      availability: 'Availability',
      customers: 'Customers',
      logout: 'Log out',
      loading: 'Loading...',
    },
    login: {
      title: 'Admin Login',
      email: 'Email',
      password: 'Password',
      submit: 'Sign in',
      submitting: 'Signing in...',
      backHome: '← Back to home',
      failed: 'Login failed',
    },
    dashboard: {
      loadError: 'Unable to load dashboard data',
      welcome: 'Welcome',
      stats: {
        todayBookings: 'Today bookings',
        weekBookings: 'This week',
        monthRevenue: 'This month revenue',
        customerCount: 'Total customers',
        pendingRescheduleRequests: 'Pending reschedules',
      },
      upcomingTitle: 'Upcoming bookings',
      emptyUpcoming: 'No upcoming bookings',
    },
    bookings: {
      title: 'Booking Management',
      detailTitle: 'Booking Details',
      loadListError: 'Unable to load bookings',
      loadDetailError: 'Unable to load booking details',
      updateSuccess: 'Booking status updated',
      updateFailed: 'Failed to update booking status',
      rescheduleSuccess: 'Booking rescheduled',
      rescheduleFailed: 'Failed to reschedule booking',
      reviewApproveSuccess: 'Reschedule request approved',
      reviewRejectSuccess: 'Reschedule request rejected',
      reviewFailed: 'Failed to review reschedule request',
      adminCancelledReason: 'Cancelled by admin',
      filters: {
        allStatuses: 'All statuses',
        searchPlaceholder: 'Search customer / email / phone',
        search: 'Search',
      },
      empty: 'No bookings match the current filters',
      selectHint: 'Select a booking on the left to view details',
      fields: {
        bookingId: 'Booking ID',
        customer: 'Customer',
        email: 'Email',
        phone: 'Phone',
        service: 'Service',
        duration: 'Duration',
        time: 'Time',
        price: 'Price',
        bookingStatus: 'Booking status',
        paymentStatus: 'Payment status',
        paymentIntent: 'Payment Intent',
        manageToken: 'Manage token',
      },
      notes: 'Customer note',
      actions: {
        confirmBooking: 'Confirm booking',
        confirmArrival: 'Confirm arrival',
        markCompleted: 'Mark completed',
        markNoShow: 'Mark no-show',
        cancelBooking: 'Cancel booking',
        submitReschedule: 'Submit reschedule',
        approve: 'Approve',
        reject: 'Reject',
      },
      attendance: {
        notArrived: 'Not arrived',
        arrived: 'Arrived',
      },
      reschedule: {
        title: 'Reschedule Manually',
        startTime: 'Start time',
        endTime: 'End time',
        adminNote: 'Admin note (optional)',
      },
      requests: {
        title: 'Reschedule Requests',
        empty: 'No reschedule requests',
        noCustomerNote: 'No customer note',
        approvePrompt: 'Review note (optional)',
        rejectPrompt: 'Rejection reason (optional)',
      },
    },
    customers: {
      title: 'Customer Management',
      detailTitle: 'Customer Details',
      loadListError: 'Unable to load customers',
      loadDetailError: 'Unable to load customer details',
      searchPlaceholder: 'Search name / email / phone',
      search: 'Search',
      empty: 'No customers found',
      selectHint: 'Select a customer on the left to view details',
      bookingCountSuffix: 'bookings',
      fields: {
        name: 'Name',
        email: 'Email',
        phone: 'Phone',
        createdAt: 'Created at',
        bookingCount: 'Booking count',
        totalSpent: 'Total spent',
      },
      historyTitle: 'Booking History',
      emptyHistory: 'No booking history',
    },
    availability: {
      title: 'Availability Management',
      loadErrorPrefix: 'Failed to load: ',
      updateHoursSuccess: 'Business hours updated',
      updateTimeSuccess: 'Hours updated',
      createBlockSuccess: 'Blocked period added',
      createBlockFailedPrefix: 'Failed to add: ',
      updateFailedPrefix: 'Update failed: ',
      deleteBlockSuccess: 'Blocked period deleted',
      deleteBlockFailedPrefix: 'Delete failed: ',
      deleteConfirm: 'Delete this blocked period?',
      businessHoursTitle: 'Business Hours',
      blocksTitle: 'Blocked Periods',
      addBlock: '+ Add blocked period',
      emptyBlocks: 'No blocked periods',
      statusOpen: 'Open',
      statusClosed: 'Closed',
      setClosed: 'Set closed',
      setOpen: 'Set open',
      delete: 'Delete',
      modal: {
        title: 'Add Blocked Period',
        startTime: 'Start time',
        endTime: 'End time',
        reason: 'Reason (optional)',
        reasonPlaceholder: 'For example: vacation, personal errand',
        cancel: 'Cancel',
        submit: 'Add',
      },
      days: ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
    },
    statuses: {
      pending: 'Pending',
      confirmed: 'Confirmed',
      arrived: 'Arrived',
      completed: 'Completed',
      cancelled: 'Cancelled',
      no_show: 'No show',
      expired: 'Expired',
      succeeded: 'Succeeded',
      failed: 'Failed',
      refunded: 'Refunded',
      partially_refunded: 'Partially refunded',
      approved: 'Approved',
      rejected: 'Rejected',
    },
    fallback: {
      notFound: 'Page not found',
    },
  },
};

export const getAdminStatusLabel = (copy, status) => {
  if (!status) {
    return copy?.common?.none ?? '-';
  }

  return copy?.statuses?.[status] ?? status;
};

export const getAdminBookingStatusBadges = (copy, status) => {
  switch (status) {
    case 'confirmed':
      return [
        { tone: 'confirmed', label: copy?.statuses?.confirmed ?? 'confirmed' },
        { tone: 'no_show', label: copy?.bookings?.attendance?.notArrived ?? copy?.statuses?.no_show ?? 'not_arrived' },
      ];
    case 'arrived':
      return [
        { tone: 'confirmed', label: copy?.statuses?.confirmed ?? 'confirmed' },
        { tone: 'arrived', label: copy?.bookings?.attendance?.arrived ?? copy?.statuses?.arrived ?? 'arrived' },
      ];
    case 'no_show':
      return [
        { tone: 'confirmed', label: copy?.statuses?.confirmed ?? 'confirmed' },
        { tone: 'no_show', label: copy?.statuses?.no_show ?? 'no_show' },
      ];
    default:
      return [
        { tone: status || 'pending', label: getAdminStatusLabel(copy, status) },
      ];
  }
};
